config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :cards, only: %i[index show]
    resources :words, only: %i[index show create update]
  end

  namespace :admin do
    resources :cards, only: %i[index]
    resources :words, only: %i[index]
    root 'home#index'
  end

  resources :cards, only: %i[show], path: :c
  resources :cards, only: %i[show]

  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  has_many :words, -> { order(:id) }, dependent: :nullify

  before_save { self.used_at ||= Time.now.utc }

  scope :search, lambda { |text|
    return all if text.blank?

    number = text.delete('^0-9').presence
    where(id: Word.distinct.search(text).select(:card_id)).or(
      number ? where('CAST(cards.id as text) LIKE ?', "%#{number}%") : none
    )
  }

  validates :words, length: { is: 5, message: 'is the wrong size (should be 5 words)' }
end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  belongs_to :card, optional: true, touch: true

  before_validation { text.squish! }

  scope :used, -> { where.not(card_id: nil) }
  scope :unused, -> { where(card_id: nil) }
  scope :search, ->(text) { text.present? ? where('LOWER(words.text) LIKE ?', "%#{text}%".downcase) : all }

  validates :text, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 2, maximum: 64 }
end

app/controllers/admin/cards_controller.rb
# frozen_string_literal: true

class Admin::CardsController < ApplicationController
  before_action :check_admin_authorization!

  def index; end
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

class Admin::HomeController < ApplicationController
  def index; end
end

app/controllers/admin/words_controller.rb
# frozen_string_literal: true

class Admin::WordsController < ApplicationController
  before_action :check_admin_authorization!

  def index; end
end

app/controllers/api/cards_controller.rb
# frozen_string_literal: true

class Api::CardsController < ApplicationController
  def index
    render json: Card.includes(:words).search(params[:search].to_s.strip).order(:id)
  end

  def show
    render json: params[:id] == 'rand' ? random_card : Card.find(params[:id])
  end
end

app/controllers/api/words_controller.rb
# frozen_string_literal: true

class Api::WordsController < ApplicationController
  before_action :check_admin_authorization!, only: %i[create update]
  after_action(only: :create) { AddCardsJob.perform_later if Word.unused.count >= 5 }

  def index
    render json: Word.search(params[:search].to_s.strip).order(:id)
  end

  def show
    render json: Word.find(params[:id])
  end

  def create
    if words_params.present?
      words = words_params.map(&Word.method(:new))
      words.each(&:save)
      words.map! { |word| word.valid? ? word : word.attributes.symbolize_keys.merge!({ errors: word.errors }) }
      return render json: words, status: (:unprocessable_entity if words.none? { |x| x.is_a? Word })
    end

    word = Word.new(word_params)
    return render json: word, status: :created if word.save
    render json: word.errors, status: :unprocessable_entity
  end

  def update
    word = Word.find(params[:id])
    return render json: word if word.update(word_params)
    render json: word.errors, status: :unprocessable_entity
  end

  private

  def word_params
    params.require(:word).permit(:text)
  end

  def words_params
    Array(params.permit(words: [:text])[:words])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  helper_method def admin_authorization?
    Rails.application.secret_key_base == (request.headers['Authorization'] || cookies['Authorization'])
  end

  def check_admin_authorization!
    return if admin_authorization?
    respond_to do |format|
      format.html { redirect_to admin_root_path }
      format.json { head :unauthorized }
    end
  end

  def random_card
    card = Card.order(:used_at).limit(Card.count / 10).sample
    raise ActiveRecord::RecordNotFound, "Couldn't find random Card" if card.nil?
    card.update(used_at: Time.now.utc)
    card
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  def show
    @card = Card.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    redirect_to card_path(random_card)
  end
end

app/views/admin/cards/index.html.erb
<div class="admin admin-cards">
  <ul>
    <li>
      <h2>#<%= controller_name.capitalize %></h2>
    </li>
    <li>
      <%= link_to(admin_root_path) do %>
        <%= image_tag('backward_arrow.png') %> Back
      <% end %>
    </li>
  </ul>
  <form id="search-cards-form" action="#" autocomplete="off">
    <input type="text" name="search" spellcheck="false">
  </form>
  <ul id="cards-list">
    <li id="dummy-card" class="card">
      <h2>#42</h2>
      <ul>
        <li><input type="text" spellcheck="false"></li>
        <div class="line"></div>
        <li><input type="text" spellcheck="false"></li>
        <div class="line"></div>
        <li><input type="text" spellcheck="false"></li>
        <div class="line"></div>
        <li><input type="text" spellcheck="false"></li>
        <div class="line"></div>
        <li><input type="text" spellcheck="false"></li>
        <div class="line"></div>
      </ul>
      <button disabled>save</button>
    </li>
  </ul>
</div>

app/views/admin/home/index.html.erb
<div class="admin admin-home">
  <h2>#Admin</h2>
  <% if admin_authorization? %>
    <ul class="centered">
      <li>
        <%= link_to(admin_cards_path) do %>
          <%= image_tag('forward_arrow.png') %> Cards
        <% end %>
      </li>
      <li>
        <%= link_to(admin_words_path) do %>
          <%= image_tag('forward_arrow.png') %> Words
        <% end %>
      </li>
      <li>
        <%= link_to(admin_root_path, id: 'logout-link') do %>
          <%= image_tag('logout.png') %> Logout
        <% end %>
      </li>
    </ul>
  <% else %>
    <form id="login-form" action="#" autocomplete="off" class="centered">
      <label for="password">Password</label>
      <input type="text" name="password" spellcheck="false">
      <button>Submit</button>
    </form>
  <% end %>
</div>

app/views/admin/words/index.html.erb
<div class="admin admin-words">
  <ul>
    <li>
      <h2>#<%= controller_name.capitalize %></h2>
    </li>
    <li>
      <%= link_to(admin_root_path) do %>
        <%= image_tag('backward_arrow.png') %> Back
      <% end %>
    </li>
  </ul>
  <form id="upload-words-form" action="#" autocomplete="off">
    <input type="text">
    <button>Upload</button>
  </form>
</div>

app/views/cards/show.html.erb
<% cache @card do %>
  <div class="card">
    <h2>#<%= @card.id %></h2>
    <ul>
      <% @card.words.sort_by(&:id).pluck(:text).map!(&:upcase_first).each do |word| %>
        <li><%= link_to(word, "https://ru.wikipedia.org/wiki/#{word}") %></li>
        <div class="line"></div>
      <% end %>
    </ul>
    <div id="card-next">
      <%= link_to('next', root_path) %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Light Words</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body data-controller="<%= controller_path %>" data-action="<%= action_name %>">
    <%= yield %>
  </body>
</html>